<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Combined migration that creates all 10 workflow tables.
 *
 * The migration reads `config('workflow.table_prefix')` at runtime, so
 * a host with a custom prefix gets the correct table names without
 * editing the file. The default prefix is `workflow_`.
 *
 * Conventions (see specs/002-laravel-workflow-engine/data-model.md §0):
 *  - `id` BIGINT PK (auto-increment)
 *  - `uuid` UUID v4 UK (generated by HasUuid trait)
 *  - Soft delete: `is_deleted` BOOLEAN + `deleted_at` TIMESTAMPTZ
 *  - Audit: `created_by`, `updated_by`, `deleted_by` BIGINT null → host users
 *  - Timestamps: `created_at`, `updated_at` TIMESTAMPTZ (EXCEPT workflow_histories)
 *  - Tenancy: `tenant_id` BIGINT null on definition + instance tables
 *  - workflow_histories is APPEND-ONLY: only `created_at` and `performed_at`,
 *    NO `updated_at`, NO soft-delete columns
 */
return new class extends Migration
{
    public function up(): void
    {
        $prefix = (string) config('workflow.table_prefix', 'workflow_');

        // --- 1. workflow_steps (must exist before workflows.start_step_id FK)
        Schema::create($prefix.'workflow_steps', function (Blueprint $table): void {
            $table->bigIncrements('id');
            $table->uuid('uuid')->unique();
            $table->unsignedBigInteger('tenant_id')->nullable();
            $table->string('name');
            $table->string('code');
            $table->text('description')->nullable();
            $table->string('type', 32); // StepType
            $table->unsignedInteger('position')->default(0);
            $table->string('authorization_mode', 32)->default('public'); // AuthorizationMode
            $table->string('match_mode', 16)->default('any'); // MatchMode
            $table->string('custom_authorizer')->nullable();
            $table->string('handler')->nullable();
            $table->boolean('is_skippable')->default(false);
            $table->boolean('is_returnable')->default(false);
            $table->unsignedInteger('sla_seconds')->nullable();
            $table->json('config')->nullable();
            $table->boolean('is_deleted')->default(false);
            $table->timestampTz('deleted_at')->nullable();
            $table->unsignedBigInteger('created_by')->nullable();
            $table->unsignedBigInteger('updated_by')->nullable();
            $table->unsignedBigInteger('deleted_by')->nullable();
            $table->timestampTz('created_at')->nullable();
            $table->timestampTz('updated_at')->nullable();

            $table->index(['tenant_id', 'code', 'deleted_at']);
            $table->index(['tenant_id', 'position']);
        });

        // --- 2. workflows
        Schema::create($prefix.'workflows', function (Blueprint $table) use ($prefix): void {
            $table->bigIncrements('id');
            $table->uuid('uuid')->unique();
            $table->unsignedBigInteger('tenant_id')->nullable();
            $table->string('name');
            $table->string('code');
            $table->text('description')->nullable();
            $table->string('type', 32); // WorkflowType
            $table->string('subject_type')->nullable();
            $table->unsignedInteger('version')->default(1);
            $table->boolean('is_current_version')->default(false);
            $table->string('status', 32)->default('draft'); // WorkflowStatus
            $table->unsignedBigInteger('start_step_id')->nullable();
            $table->boolean('require_explicit_transitions')->default(false);
            $table->json('config')->nullable();
            $table->boolean('is_deleted')->default(false);
            $table->timestampTz('deleted_at')->nullable();
            $table->unsignedBigInteger('created_by')->nullable();
            $table->unsignedBigInteger('updated_by')->nullable();
            $table->unsignedBigInteger('deleted_by')->nullable();
            $table->timestampTz('created_at')->nullable();
            $table->timestampTz('updated_at')->nullable();

            $table->foreign('start_step_id')
                ->references('id')->on($prefix.'workflow_steps')
                ->onDelete('set null');

            $table->unique(['tenant_id', 'code', 'deleted_at'], 'workflows_tenant_code_deleted_uq');
            $table->index('status');
            $table->index('subject_type');
        });

        // --- 3. workflow_step_assignees
        Schema::create($prefix.'workflow_step_assignees', function (Blueprint $table) use ($prefix): void {
            $table->bigIncrements('id');
            $table->uuid('uuid')->unique();
            $table->unsignedBigInteger('step_id');
            $table->string('assignee_type', 32); // AssigneeType
            $table->string('assignee_value')->nullable();
            $table->string('custom_resolver')->nullable();
            $table->unsignedInteger('sort_order')->default(0);
            $table->boolean('is_deleted')->default(false);
            $table->timestampTz('deleted_at')->nullable();
            $table->unsignedBigInteger('created_by')->nullable();
            $table->unsignedBigInteger('updated_by')->nullable();
            $table->unsignedBigInteger('deleted_by')->nullable();
            $table->timestampTz('created_at')->nullable();
            $table->timestampTz('updated_at')->nullable();

            $table->foreign('step_id')
                ->references('id')->on($prefix.'workflow_steps')
                ->onDelete('cascade');

            $table->index(['step_id', 'sort_order']);
        });

        // --- 4. workflow_conditions (no FK to workflow yet; workflow is created above)
        Schema::create($prefix.'workflow_conditions', function (Blueprint $table) use ($prefix): void {
            $table->bigIncrements('id');
            $table->uuid('uuid')->unique();
            $table->unsignedBigInteger('workflow_id')->nullable();
            $table->string('name');
            $table->string('code');
            $table->string('kind', 32); // ConditionKind
            $table->json('expression')->nullable();
            $table->string('evaluator')->nullable();
            $table->boolean('is_deleted')->default(false);
            $table->timestampTz('deleted_at')->nullable();
            $table->unsignedBigInteger('created_by')->nullable();
            $table->unsignedBigInteger('updated_by')->nullable();
            $table->unsignedBigInteger('deleted_by')->nullable();
            $table->timestampTz('created_at')->nullable();
            $table->timestampTz('updated_at')->nullable();

            $table->foreign('workflow_id')
                ->references('id')->on($prefix.'workflows')
                ->onDelete('cascade');

            $table->index(['workflow_id', 'code']);
            $table->index('kind');
        });

        // --- 5. workflow_step_actions
        Schema::create($prefix.'workflow_step_actions', function (Blueprint $table) use ($prefix): void {
            $table->bigIncrements('id');
            $table->uuid('uuid')->unique();
            $table->unsignedBigInteger('step_id');
            $table->string('name');
            $table->string('code');
            $table->string('label')->nullable();
            $table->string('type', 32); // ActionType
            $table->string('availability_mode', 32)->default('general'); // ActionAvailabilityMode
            $table->unsignedBigInteger('guard_condition_id')->nullable();
            $table->string('guard_class')->nullable();
            $table->unsignedBigInteger('target_step_id')->nullable();
            $table->boolean('requires_comment')->default(false);
            $table->string('handler')->nullable();
            $table->unsignedInteger('sort_order')->default(0);
            $table->boolean('is_deleted')->default(false);
            $table->timestampTz('deleted_at')->nullable();
            $table->unsignedBigInteger('created_by')->nullable();
            $table->unsignedBigInteger('updated_by')->nullable();
            $table->unsignedBigInteger('deleted_by')->nullable();
            $table->timestampTz('created_at')->nullable();
            $table->timestampTz('updated_at')->nullable();

            $table->foreign('step_id')
                ->references('id')->on($prefix.'workflow_steps')
                ->onDelete('cascade');

            $table->foreign('guard_condition_id')
                ->references('id')->on($prefix.'workflow_conditions')
                ->onDelete('set null');

            $table->foreign('target_step_id')
                ->references('id')->on($prefix.'workflow_steps')
                ->onDelete('set null');

            $table->index(['step_id', 'code']);
            $table->index(['step_id', 'sort_order']);
        });

        // --- 6. workflow_transitions
        Schema::create($prefix.'workflow_transitions', function (Blueprint $table) use ($prefix): void {
            $table->bigIncrements('id');
            $table->uuid('uuid')->unique();
            $table->unsignedBigInteger('workflow_id');
            $table->unsignedBigInteger('from_step_id')->nullable();
            $table->unsignedBigInteger('to_step_id')->nullable();
            $table->unsignedBigInteger('action_id')->nullable();
            $table->unsignedBigInteger('condition_id')->nullable();
            $table->string('type', 32); // TransitionType
            $table->integer('priority')->default(0);
            $table->boolean('is_deleted')->default(false);
            $table->timestampTz('deleted_at')->nullable();
            $table->unsignedBigInteger('created_by')->nullable();
            $table->unsignedBigInteger('updated_by')->nullable();
            $table->unsignedBigInteger('deleted_by')->nullable();
            $table->timestampTz('created_at')->nullable();
            $table->timestampTz('updated_at')->nullable();

            $table->foreign('workflow_id')
                ->references('id')->on($prefix.'workflows')
                ->onDelete('cascade');

            $table->foreign('from_step_id')
                ->references('id')->on($prefix.'workflow_steps')
                ->onDelete('set null');

            $table->foreign('to_step_id')
                ->references('id')->on($prefix.'workflow_steps')
                ->onDelete('set null');

            $table->foreign('action_id')
                ->references('id')->on($prefix.'workflow_step_actions')
                ->onDelete('set null');

            $table->foreign('condition_id')
                ->references('id')->on($prefix.'workflow_conditions')
                ->onDelete('set null');

            $table->index(['workflow_id', 'from_step_id']);
            $table->index('action_id');
        });

        // --- 7. workflow_instances
        Schema::create($prefix.'workflow_instances', function (Blueprint $table) use ($prefix): void {
            $table->bigIncrements('id');
            $table->uuid('uuid')->unique();
            $table->unsignedBigInteger('tenant_id')->nullable();
            $table->unsignedBigInteger('workflow_id');
            $table->unsignedInteger('workflow_version');
            $table->string('subject_type');
            $table->unsignedBigInteger('subject_id');
            $table->unsignedBigInteger('current_step_id')->nullable();
            $table->string('status', 32)->default('pending'); // InstanceStatus
            $table->json('context')->nullable();
            $table->unsignedBigInteger('initiated_by')->nullable();
            $table->timestampTz('started_at')->nullable();
            $table->timestampTz('completed_at')->nullable();
            $table->boolean('is_deleted')->default(false);
            $table->timestampTz('deleted_at')->nullable();
            $table->unsignedBigInteger('created_by')->nullable();
            $table->unsignedBigInteger('updated_by')->nullable();
            $table->unsignedBigInteger('deleted_by')->nullable();
            $table->timestampTz('created_at')->nullable();
            $table->timestampTz('updated_at')->nullable();

            $table->foreign('workflow_id')
                ->references('id')->on($prefix.'workflows')
                ->onDelete('restrict');

            $table->foreign('current_step_id')
                ->references('id')->on($prefix.'workflow_steps')
                ->onDelete('set null');

            $table->index(['subject_type', 'subject_id']);
            $table->index(['workflow_id', 'status']);
            $table->index('status');
            $table->index('tenant_id');
        });

        // --- 8. workflow_step_instances
        Schema::create($prefix.'workflow_step_instances', function (Blueprint $table) use ($prefix): void {
            $table->bigIncrements('id');
            $table->uuid('uuid')->unique();
            $table->unsignedBigInteger('workflow_instance_id');
            $table->unsignedBigInteger('step_id');
            $table->string('status', 32)->default('pending'); // StepInstanceStatus
            $table->timestampTz('entered_at')->nullable();
            $table->timestampTz('completed_at')->nullable();
            $table->timestampTz('due_at')->nullable();
            $table->unsignedBigInteger('acted_by')->nullable();
            $table->string('action_taken')->nullable();
            $table->text('comment')->nullable();
            $table->json('data')->nullable();
            $table->boolean('is_deleted')->default(false);
            $table->timestampTz('deleted_at')->nullable();
            $table->unsignedBigInteger('created_by')->nullable();
            $table->unsignedBigInteger('updated_by')->nullable();
            $table->unsignedBigInteger('deleted_by')->nullable();
            $table->timestampTz('created_at')->nullable();
            $table->timestampTz('updated_at')->nullable();

            $table->foreign('workflow_instance_id')
                ->references('id')->on($prefix.'workflow_instances')
                ->onDelete('cascade');

            $table->foreign('step_id')
                ->references('id')->on($prefix.'workflow_steps')
                ->onDelete('restrict');

            $table->index(['workflow_instance_id', 'status']);
        });

        // --- 9. workflow_assignments
        Schema::create($prefix.'workflow_assignments', function (Blueprint $table) use ($prefix): void {
            $table->bigIncrements('id');
            $table->uuid('uuid')->unique();
            $table->unsignedBigInteger('step_instance_id');
            $table->unsignedBigInteger('assignee_id');
            $table->string('status', 32)->default('pending'); // AssignmentStatus
            $table->timestampTz('assigned_at')->nullable();
            $table->timestampTz('acted_at')->nullable();
            $table->boolean('is_deleted')->default(false);
            $table->timestampTz('deleted_at')->nullable();
            $table->unsignedBigInteger('created_by')->nullable();
            $table->unsignedBigInteger('updated_by')->nullable();
            $table->unsignedBigInteger('deleted_by')->nullable();
            $table->timestampTz('created_at')->nullable();
            $table->timestampTz('updated_at')->nullable();

            $table->foreign('step_instance_id')
                ->references('id')->on($prefix.'workflow_step_instances')
                ->onDelete('cascade');

            $table->index(['assignee_id', 'status']);
            $table->index(['step_instance_id', 'status']);
        });

        // --- 10. workflow_histories (APPEND-ONLY — no updated_at, no soft delete)
        Schema::create($prefix.'workflow_histories', function (Blueprint $table) use ($prefix): void {
            $table->bigIncrements('id');
            $table->uuid('uuid')->unique();
            $table->unsignedBigInteger('workflow_instance_id');
            $table->unsignedBigInteger('step_instance_id')->nullable();
            $table->unsignedBigInteger('from_step_id')->nullable();
            $table->unsignedBigInteger('to_step_id')->nullable();
            $table->string('action_code')->nullable();
            $table->string('event', 32); // HistoryEvent
            $table->unsignedBigInteger('actor_id')->nullable();
            $table->string('actor_type', 32)->default('user'); // ActorType
            $table->text('comment')->nullable();
            $table->json('metadata')->nullable();
            $table->timestampTz('performed_at');
            $table->timestampTz('created_at')->useCurrent();

            $table->foreign('workflow_instance_id')
                ->references('id')->on($prefix.'workflow_instances')
                ->onDelete('cascade');

            $table->foreign('step_instance_id')
                ->references('id')->on($prefix.'workflow_step_instances')
                ->onDelete('set null');

            $table->foreign('from_step_id')
                ->references('id')->on($prefix.'workflow_steps')
                ->onDelete('set null');

            $table->foreign('to_step_id')
                ->references('id')->on($prefix.'workflow_steps')
                ->onDelete('set null');

            $table->index(['workflow_instance_id', 'performed_at']);
            $table->index('event');
            $table->index(['actor_id', 'performed_at']);
        });
    }

    public function down(): void
    {
        $prefix = (string) config('workflow.table_prefix', 'workflow_');

        // Drop in reverse dependency order
        Schema::dropIfExists($prefix.'workflow_histories');
        Schema::dropIfExists($prefix.'workflow_assignments');
        Schema::dropIfExists($prefix.'workflow_step_instances');
        Schema::dropIfExists($prefix.'workflow_instances');
        Schema::dropIfExists($prefix.'workflow_transitions');
        Schema::dropIfExists($prefix.'workflow_step_actions');
        Schema::dropIfExists($prefix.'workflow_conditions');
        Schema::dropIfExists($prefix.'workflow_step_assignees');
        Schema::dropIfExists($prefix.'workflows');
        Schema::dropIfExists($prefix.'workflow_steps');
    }
};
